name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: composer install
      - run: echo /home/linuxbrew/.linuxbrew/bin >> $GITHUB_PATH
      - run: |
          brew install seaweedfs
          cd ~
          weed mini -tableBucket=seaduck-php-test &
      - uses: ankane/setup-postgres@v1
        with:
          database: seaduck_php_test
      - run: composer test
